from .buttons import BUTTON_BINDINGS
from .enables import ENABLE_BINDINGS
from .gas import GAS_BINDINGS
from .mode import MODE_BINDINGS, MODE_WRITE_BINDINGS
from .q_status import Q_STATUS_BINDINGS
from .servo import SERVO_M_BINDINGS, SERVO_V_BINDINGS
from .settings import SETTINGS_LIMIT_BINDINGS, SETTINGS_RUN_MODE_BINDINGS
from .signals import SIGNAL_BINDINGS
from .torque import TORQUE_BINDINGS

ALL_BINDINGS = (
    SIGNAL_BINDINGS
    + Q_STATUS_BINDINGS
    + MODE_BINDINGS
    + MODE_WRITE_BINDINGS
    + BUTTON_BINDINGS
    + ENABLE_BINDINGS
    + SERVO_M_BINDINGS
    + SERVO_V_BINDINGS
    + TORQUE_BINDINGS
    + SETTINGS_RUN_MODE_BINDINGS
    + SETTINGS_LIMIT_BINDINGS
    + GAS_BINDINGS
)

READ_BINDINGS = [binding for binding in ALL_BINDINGS if binding.direction == "read"]
WRITE_BINDINGS = [binding for binding in ALL_BINDINGS if binding.direction == "write"]

__all__ = [
    "SIGNAL_BINDINGS",
    "Q_STATUS_BINDINGS",
    "MODE_BINDINGS",
    "MODE_WRITE_BINDINGS",
    "BUTTON_BINDINGS",
    "ENABLE_BINDINGS",
    "SERVO_M_BINDINGS",
    "SERVO_V_BINDINGS",
    "TORQUE_BINDINGS",
    "SETTINGS_RUN_MODE_BINDINGS",
    "SETTINGS_LIMIT_BINDINGS",
    "GAS_BINDINGS",
    "ALL_BINDINGS",
    "READ_BINDINGS",
    "WRITE_BINDINGS",
]
